# Generated by Django 6.1 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=30, verbose_name="Имя"),
        ),
    ]
